version: '3.3'
services:
  # Back-End
  marvel-backend:
    container_name: marvel-api
    image: marvel_api
    build:
      context: .
    ports:
      - '8080:8080'

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-marvel
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_db:/var/lib/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'

  # Grafana
  grafana:
    image: grafana/grafana
    container_name: grafana-marvel
    restart: unless-stopped
    user: '1000'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secure_pass
    volumes:
      - ./grafana_db:/var/lib/grafana
    depends_on:
      - prometheus
    ports:
      - '3000:3000'

networks:
  default:
    external:
      name: gateway_marvel_net