version: "3.3"
services:
  marvel-backend:
    container_name: marvel-api
    image: marvel_api
    build:
      context: .
    networks:
      - marvel_net
    ports:
      - 443:443

networks:
  marvel_net: