global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'host.docker.internal:9090' ]

  - job_name: 'gateway'
    scrape_interval: 10s
    metrics_path: 'actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]