global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: [ 'host.docker.internal:9090' ]

  - job_name: 'gateway'
    scrape_interval: 10s
    metrics_path: 'actuator/prometheus'
    tls_config:
      insecure_skip_verify: false
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]