info:
  app:
    version: '@project.version@'

spring:
  application:
    name: 'heroes'
  servlet:
    context-path: '/v1/public'
  profiles:
    active: test
  banner:
    location: classpath:/banner.txt

management:
  endpoints:
    web:
      exposure:
        include: '*'