info:
  app:
    version: '@project.version@'

spring:
  application:
    name: 'heroes'
  profiles:
    active: test
  banner:
    location: classpath:/banner.txt

management:
  endpoints:
    web:
      exposure:
        include: '*'